---
kind: pipeline
type: docker
name: network-automation

steps:
- name: terraform-init
  image: hashicorp/terraform:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: MINIO_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: MINIO_SECRET_KEY
    AWS_ENDPOINT_URL_S3:
      from_secret: MINIO_ENDPOINT
  commands:
    - terraform init
  
- name: terraform-validate
  image: hashicorp/terraform:latest
  commands:
    - terraform validate

- name: terraform-plan
  image: hashicorp/terraform:latest
  environment:
    TF_VAR_username:
      from_secret: tf_username
    TF_VAR_password:
      from_secret: tf_password
    AWS_ACCESS_KEY_ID:
      from_secret: MINIO_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: MINIO_SECRET_KEY
    AWS_ENDPOINT_URL_S3:
      from_secret: MINIO_ENDPOINT
    TF_VAR_netbox_url:
      from_secret: netbox_url
    TF_VAR_netbox_token:
      from_secret: netbox_token
  commands:
    - terraform plan -out=tfplan

- name: terraform-apply
  image: hashicorp/terraform:latest
  environment:
    TF_VAR_username:
      from_secret: tf_username
    TF_VAR_password:
      from_secret: tf_password
    AWS_ACCESS_KEY_ID:
      from_secret: MINIO_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY:
      from_secret: MINIO_SECRET_KEY
    AWS_ENDPOINT_URL_S3:
      from_secret: MINIO_ENDPOINT
    TF_VAR_netbox_url:
      from_secret: netbox_url
    TF_VAR_netbox_token:
      from_secret: netbox_token
  commands:
    - terraform apply -auto-approve tfplan